DB_NAME: areadb
DB_SERVER: localhost
DB_PORT: 5432
DB_USERNAME: andr
DB_PASSWORD: 123456

server:
  port: 8089

spring:
  datasource:
    url: jdbc:postgresql://${DB_SERVER}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      hibernate:
        sql: debug
        orm:
          jdbc:
            bind: trace

#  logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE